export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";

export const FETCH_PRODUCT_PENDING = "FETCH_PRODUCT_PENDING";

export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE";

export const SAVE_PRODUCT_SUCCESS = "SAVE_PRODUCT_SUCCESS";

export const SAVE_PRODUCT_PENDING = "SAVE_PRODUCT_PENDING";

export const SAVE_PRODUCT_FAILURE = "SAVE_PRODUCT_FAILURE";
